# Site settings
title: "گزارش ا.پ."
description: ""
baseurl: "." # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: ""

# Build settings
kramdown:
  input: GFM
permalink: :title.html

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:

plugins:
  - jekyll-sitemap
